"use client";

import React from "react";
import { useRef, useState, useEffect } from "react";
import "./globals.css";
import {
  CircleUser,
  Search,
  Bot,
  HeartHandshake,
  Database,
  MessageSquareMore,
  FileText,
  ScrollText,
  Globe,
} from "lucide-react";

export default function Home() {
  const menuRef = useRef(null);
  const headerRef = useRef(null);

  const tabData = [
    {
      id: "tab7",
      title: "Retrieval Augmented Generation (RAG) Explained",
      description:
        "Retrieval Augmented Generation (RAG) is an AI framework designed to enhance the accuracy of responses generated by LLMs. It achieves this by incorporating external sources of knowledge to complement the model's internal understanding.",
      imgUrl:
        "https://squirro.com/hubfs/Retrieval%20Augmented%20Generation%20%28RAG%29%20Explained.jpg",
      listItems: [
        "SquirroGPT uses RAG technology. It uses Squirro's Semantic Search before it queries the Large Language Model (LLM).",
        "Once the user enters a prompt, SquirroGPT queries the knowledge base - the data and documents ingested.",
        "SquirroGPT then sends relevant information with the query to the LLM.",
        "As an extra layer of verification, the response is validated against the knowledge base before passing the answer back to the user.",
      ],
      imgAlt: "RAG Explained",
      icon: "Database",
    },
    {
      id: "tab1",
      title: "SquirroGPT Chat Conversation",
      description:
        "SquirroGPT allows chatting with all organizational data, ensuring each answer is supported by evidence and can be embedded for a wider audience.",
      imgUrl:
        "https://squirro.com/hubfs/SquirroGPT%20Chat%20Conversation_1.jpg",
      imgAlt: "SquirroGPT Chat Conversation",
      icon: "MessageSquareMore",
    },
    {
      id: "tab2",
      title: "Chat with Results",
      description:
        "This feature enables interaction with data of interest without opening documents, using RAG technology to provide precise results by analyzing relevant paragraphs.",
      imgUrl: "https://squirro.com/hubfs/Chat%20With%20Results.jpg",
      imgAlt: "Chat with Results",
      icon: "Search",
    },
    {
      id: "tab3",
      title: "Chat With Documents",
      description:
        "Engage with documents conversationally, retrieve information from a single document, and verify answers by cross-referencing with highlighted text in the document.",
      imgUrl: "https://squirro.com/hubfs/Chat%20With%20Documents.jpg",
      imgAlt: "Chat With Documents",
      icon: "FileText",
    },
    {
      id: "tab4",
      title: "Summarize Documents",
      description:
        "Supports four types of document summarization—document, topical, page, and selection summaries—with options to personalize summaries.",
      imgUrl: "https://squirro.com/hubfs/Summarize%20Documents.jpg",
      imgAlt: "Summarize Documents",
      icon: "ScrollText",
    },
    {
      id: "tab5",
      title: "Search & Chat while Browsing",
      description:
        "Combine workplace search with contextually aware chat to interact with internal and external data sources and generate personalized insights.",
      imgUrl:
        "https://squirro.com/hubfs/Search%20&%20Chat%20while%20Browsing.jpg",
      imgAlt: "Search & Chat while Browsing",
      icon: "Globe",
    },
    {
      id: "tab6",
      title: "Chat with Structured Data",
      description:
        "Analyze and visualize structured data through the chat interface, allowing users to parse and draw conclusions from large datasets by asking questions.",
      imgUrl: "https://squirro.com/hubfs/Chat%20with%20Structured%20Data.jpg",
      imgAlt: "Chat with Structured Data",
      icon: "MessageSquareMore",
    },
  ];

  const iconMapping = {
    MessageSquareMore: MessageSquareMore,
    Search: Search,
    Bot: Bot,
    HeartHandshake: HeartHandshake,
    Database: Database,
    FileText: FileText,
    ScrollText: ScrollText,
    Globe: Globe,
  };

  const [menuActive, setMenuActive] = useState(null);
  const [isScrolled, setIsScrolled] = useState(false);
  const [activeTab, setActiveTab] = useState(tabData[0].id);
  const [backgroundStyle, setBackgroundStyle] = useState({});
  const tabsRef = useRef([]);
  const backgroundRef = useRef();

  useEffect(() => {
    const activeTabIndex = tabData.findIndex((tab) => tab.id === activeTab);
    const tabElement = tabsRef.current[activeTabIndex];
    if (tabElement) {
      const { offsetTop, offsetHeight } = tabElement;
      setBackgroundStyle({
        top: `${offsetTop}px`,
        height: `${offsetHeight}px`,
      });
    }
  }, [activeTab]);

  useEffect(() => {
    const tabElement = tabsRef.current[0];
    if (tabElement) {
      const { offsetTop, offsetHeight } = tabElement;
      setBackgroundStyle({
        top: `${offsetTop}px`,
        height: `${offsetHeight}px`,
      });
    }
  }, []);

  useEffect(() => {
    const activeTabIndex = tabData.findIndex((tab) => tab.id === activeTab);
    const tabElement = tabsRef.current[activeTabIndex];
    if (tabElement) {
      const { offsetTop, offsetHeight } = tabElement;
      const newStyle = {
        top: `${offsetTop}px`,
        height: `${offsetHeight}px`,
      };
      if (
        backgroundStyle.top !== newStyle.top ||
        backgroundStyle.height !== newStyle.height
      ) {
        setBackgroundStyle(newStyle);
      }
    }
  }, [activeTab, tabData, backgroundStyle]);
  const handleMouseOver = (idx) => {
    if (menuActive !== idx) {
      setMenuActive(idx);
      const heights = [400, 350, 450, 320]; // heights for each submenu
      menuRef.current.style.height = `${heights[idx]}px`;
    }
  };

  const handleMouseOut = (event) => {
    // Check if the mouse is still within the menuRoot or its children
    if (!menuRef.current.contains(event.relatedTarget)) {
      setMenuActive(null);
      menuRef.current.style.height = "0";
    }
  };

  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 50) {
        setIsScrolled(true);
      } else {
        setIsScrolled(false);
      }
    };

    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  const handleVideoError = (e) => {
    console.error("Video failed to load:", e);
  };

  return (
    <>
      <header
        ref={headerRef}
        className={`header-wrapper  ${isScrolled ? "scrolled" : ""}`}
      >
        <div
          className="menuRoot sm:px-7 px-4"
          ref={menuRef}
          onMouseLeave={handleMouseOut}
        >
          <div
            className={`menuOne  subMenus ${menuActive === 0 ? "active" : ""}`}
          >
            <div className="sub-menu-content-wrapper">
              <h1>Solutions</h1>
              <p className="sub-content-wrapper">
                Discover How Squirro's AI & Semantic Search Is Revolutionizing
                Enterprise Search. Transform Your Data Strategy Now!
              </p>
              <button className="demoButton">Read Our Buyer's Guide</button>
            </div>
            <ul>
              <li>
                <Bot size={28} color="#001D32" strokeWidth={1} />
                <span>SquirroGPT</span>
              </li>
              <li>
                <Bot size={28} color="#001D32" strokeWidth={1} />
                <span>Knowledge Management</span>
              </li>
              <li>
                <Bot size={28} color="#001D32" strokeWidth={1} />
                <span>Risk, Compliance & Audit</span>
              </li>
              <li>
                <Bot size={28} color="#001D32" strokeWidth={1} />
                <span>Service Management</span>
              </li>
              <li>
                <Bot size={28} color="#001D32" strokeWidth={1} />
                <span>Sales Management</span>
              </li>
            </ul>
          </div>
          <div
            className={`menuTwo subMenus ${menuActive === 1 ? "active" : ""}`}
            onMouseOver={() => handleMouseOver(1)}
          >
            <div className="sub-menu-content-wrapper">
              <h1>The Core Technology</h1>
              <p className="sub-content-wrapper">
                Unlock the potential of the Insight Engine to craft intelligent,
                tailored solutions using the ready-to-use building blocks.
              </p>
              <button className="demoButton">Start for Free</button>
            </div>
            <ul>
              <li>
                <Bot size={28} color="#001D32" strokeWidth={1} />
                <span>Insight Engine</span>
              </li>
              <li>
                <Bot size={28} color="#001D32" strokeWidth={1} />
                <span>Enterprise Search</span>
              </li>
              <li>
                <Bot size={28} color="#001D32" strokeWidth={1} />
                <span>Data Classification</span>
              </li>
            </ul>
          </div>
          <div
            className={`menuThree subMenus ${menuActive === 2 ? "active" : ""}`}
          >
            <div className="sub-menu-content-wrapper">
              <h1>Your source for the latest about AI for business</h1>
            </div>
            <ul>
              <li>
                <Bot size={28} color="#001D32" strokeWidth={1} />
                <span>Blog</span>
              </li>
              <li>
                <Bot size={28} color="#001D32" strokeWidth={1} />
                <span>News & Events</span>
              </li>
              <li>
                <Bot size={28} color="#001D32" strokeWidth={1} />
                <span>Podcast</span>
              </li>
              <li>
                <Bot size={28} color="#001D32" strokeWidth={1} />
                <span>Resources</span>
              </li>
              <li>
                <Bot size={28} color="#001D32" strokeWidth={1} />
                <span>Academy</span>
              </li>
              <li>
                <Bot size={28} color="#001D32" strokeWidth={1} />
                <span>Documentation</span>
              </li>
              <li>
                <Bot size={28} color="#001D32" strokeWidth={1} />
                <span>Forum</span>
              </li>
            </ul>
            <div className="sub-menu-cta">
              <a href="/blog">
                <img
                  src="https://squirro.com/hs-fs/hubfs/Imported_Blog_Media/Featured-image-A-BETTER-APPROACH-TO-THE-MYTH-OF-EASY-SOLUTIONS-Blog-post-September-2023-1.jpg?width=1580&name=Featured-image-A-BETTER-APPROACH-TO-THE-MYTH-OF-EASY-SOLUTIONS-Blog-post-September-2023-1.jpg"
                  alt="blog post image"
                />
                <p>A Better Approach to the Myth of Easy Solutions</p>
                <span>Learn More</span>
              </a>
            </div>
          </div>
          <div
            className={`menuFour subMenus ${menuActive === 3 ? "active" : ""}`}
          >
            <ul>
              <li>
                <Bot size={28} color="#001D32" strokeWidth={1} />
                <span>Customers</span>
              </li>
              <li>
                <Bot size={28} color="#001D32" strokeWidth={1} />
                <span>About Us</span>
              </li>
              <li>
                <Bot size={28} color="#001D32" strokeWidth={1} />
                <span>Partners</span>
              </li>
              <li>
                <Bot size={28} color="#001D32" strokeWidth={1} />
                <span>Careers</span>
              </li>
              <li>
                <Bot size={28} color="#001D32" strokeWidth={1} />
                <span>Contact</span>
              </li>
            </ul>
          </div>
        </div>
        <div className="menu-wrapper mx-auto sm:px-7 px-4 max-w-screen-xl">
          <div className="left-menu">
            <div className="logo-wrapper">
              <img
                src="https://squirro.com/hs-fs/hubfs/squirro_logo_normal_color-1.png?width=300&height=78&name=squirro_logo_normal_color-1.png"
                alt="logo"
              />
            </div>
            <div className="menuWrap nav">
              <ul className="menuList">
                <li
                  id="menuOneId"
                  onMouseOver={() => handleMouseOver(0)}
                  onMouseOut={handleMouseOut}
                >
                  <a href="#" className="linkList">
                    Solutions
                  </a>
                </li>
                <li
                  id="menuTwoId"
                  onMouseOver={() => handleMouseOver(1)}
                  onMouseOut={handleMouseOut}
                >
                  <a href="#" className="linkList">
                    Platform
                  </a>
                </li>
                <li>
                  <a href="#" className="linkList">
                    Pricing
                  </a>
                </li>
                <li
                  id="menuThreeId"
                  onMouseOver={() => handleMouseOver(2)}
                  onMouseOut={handleMouseOut}
                >
                  <a href="#" className="linkList">
                    Knowledge Hub
                  </a>
                </li>
                <li
                  id="menuFourId"
                  onMouseOver={() => handleMouseOver(3)}
                  onMouseOut={handleMouseOut}
                >
                  <a href="#" className="linkList">
                    About Us
                  </a>
                </li>
              </ul>
            </div>
          </div>

          <div className="right-menu-wrapper">
            <button className="demoButton">Book a Demo</button>
            <div className="iconContainer">
              <Search
                size={36}
                color="#001d32"
                strokeWidth={1.25}
                absoluteStrokeWidth
                fill="none"
              />
              <CircleUser
                size={36}
                color="#001d32"
                strokeWidth={1.25}
                absoluteStrokeWidth
                fill="none"
              />
            </div>
          </div>
        </div>
      </header>
      <main className="main-content mx-auto sm:px-7 px-4 max-w-screen-xl">
        <section className="">
          <div className="relative">
            <div className=" mx-auto max-w-screen-xl mt-[10px] mb-[55px]">
              <div className="gap-x-0 pt-[135px] pb-0 md:pb-16 mb-[-20px] lg:mb-0 mx-auto mt-4 lg:pt-20 lg:grid xl:px-0 lg:grid-cols-16">
                <div className="mt-3 lg:col-span-8 lg:mt-6">
                  <h2 className="mb-0 text-5xl font-bold text-[#d14a20] lg:text-7xl">
                    Where Data Finds Purpose
                  </h2>
                </div>
                <div className="lg:col-start-9 lg:col-span-1">
                  <p className="max-w-3xl mt-4 text-[24px] leading-[26px] lg:mt-8">
                    Enterprise-Ready Generative AI for Search, Insights, and
                    Automation
                  </p>
                  <div className="flex mt-8 space-x-2 md:space-x-6">
                    <div className="btn-wrapper btn-primary-wrapper btn-wrapper-lg">
                      <a
                        className="cta-button"
                        href="https://squirro.com/squirrogpt"
                      >
                        SquirroGPT
                      </a>
                    </div>
                    <div className="btn-wrapper btn-outline-primary-wrapper btn-wrapper-lg">
                      <a
                        className="cta-button"
                        href="https://squirro.com/book-a-demo"
                      >
                        Book a Demo
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="mx-auto dark:text-white max-w-screen-xl">
              <div className="relative z-10 max-md:px-4">
                <div className="z-0 overflow-hidden max-md:mt-20 rounded-3xl smaller-video">
                  <div className="z-0 overflow-hidden aspect-w-16 aspect-h-6 bg-neutrals-light-14 rounded-2xl lg:rounded-[8px]"></div>
                  <video
                    className="responsive-video-file"
                    loading="lazy"
                    preload="none"
                    aria-describedby="VideoPoster-SquirroGPT EnterpriseSearch-1123"
                    autoPlay
                    loop
                    muted
                    playsInline
                    poster="https://139651395.fs1.hubspotusercontent-eu1.net/hubfs/139651395/WEBSITE/Homepage/VideoPoster-SquirroGPT%20EnterpriseSearch-1123.webp"
                    onError={handleVideoError}
                  >
                    <source
                      src="https://squirro.com/hubfs/WEBSITE/Homepage/HeroVideo-SquirroGPT%20EnterpriseSearch-1123_Final.webm"
                      type="video/webm"
                    />
                    <source
                      src="https://139651395.fs1.hubspotusercontent-eu1.net/hubfs/139651395/WEBSITE/Homepage/HeroVideo-SquirroGPT%20Enterprise%20Search-1123-Final.mp4"
                      type="video/mp4; codecs=hevc"
                    />
                    <source
                      src="https://139651395.fs1.hubspotusercontent-eu1.net/hubfs/139651395/WEBSITE/Homepage/HeroVideo-SquirroGPT%20Enterprise%20Search-1123-Final.mp4"
                      type="video/mp4"
                    />
                  </video>
                </div>
              </div>
            </div>
          </div>
        </section>
        <div className="mt-32">
          <div className="ref-slider">
            <div className="mx-auto max-w-screen-xl">
              <div className="grid items-center lg:grid-cols-4">
                <div className="relative font-bold text-4xl text-center lg:text-left lg:max-w-[300px]">
                  <p className="mb-8 sm:mb-0"> Customers Trusting Squirro</p>
                  <HeartHandshake
                    size={42}
                    className="absolute top-0 right-0 hidden lg:block"
                    color="#d14a20"
                    strokeWidth={1}
                    absoluteStrokeWidth
                    opacity={0.4}
                  />
                </div>
                <div className="slider-container lg:col-span-3">
                  <div className="image-slider">
                    <img
                      src="https://squirro.com/hubfs/WEBSITE/Global%20assets/Logostrip%20logos/Logo-SRGSSR-1023.svg"
                      alt="SRG SSR Logo"
                      height="106"
                      width="179"
                      loading="lazy"
                    />
                    <img
                      src="https://squirro.com/hubfs/WEBSITE/Global%20assets/Logostrip%20logos/Logo-Evalueserve-1023.svg"
                      alt="Evalueserve Logo"
                      height="106"
                      width="179"
                      loading="lazy"
                    />
                    <img
                      src="https://squirro.com/hubfs/WEBSITE/Global%20assets/Logostrip%20logos/Logo-DeutscheBundesBankEuroSystem-1023.svg"
                      alt="Deutsche Bundesbank Logo"
                      height="106"
                      width="179"
                      loading="lazy"
                    />
                    <img
                      src="https://squirro.com/hubfs/WEBSITE/Global%20assets/Logostrip%20logos/Logo-loc-1223.svg"
                      alt="Library of Congress Logo"
                      height="106"
                      width="179"
                      loading="lazy"
                    />
                    <img
                      src="https://squirro.com/hubfs/WEBSITE/Global%20assets/Logostrip%20logos/Logo-Ansys-1123.svg"
                      alt="Ansys Logo"
                      height="106"
                      width="179"
                      loading="lazy"
                    />
                    <img
                      src="https://squirro.com/hubfs/WEBSITE/Global%20assets/Logostrip%20logos/Logo-BankOfEngland-1023.svg"
                      alt="Bank of England Logo"
                      height="106"
                      width="179"
                      loading="lazy"
                    />
                    <img
                      src="https://squirro.com/hubfs/WEBSITE/Global%20assets/Logostrip%20logos/Logo-BertelsmannFoundation-1023.svg"
                      alt="Bertelsmann Foundation"
                      height="106"
                      width="179"
                      loading="lazy"
                    />
                    <img
                      src="https://squirro.com/hubfs/WEBSITE/Global%20assets/Logostrip%20logos/Logo-StandardChartered-1023.svg"
                      alt="Standard Chartered Logo"
                      height="106"
                      width="179"
                      loading="lazy"
                    />
                    <img
                      src="https://squirro.com/hubfs/WEBSITE/Global%20assets/Logostrip%20logos/Logo-Natwest-123.svg"
                      alt="NatWest Logo"
                      height="106"
                      width="179"
                      loading="lazy"
                    />
                    <img
                      src="https://squirro.com/hubfs/WEBSITE/Global%20assets/Logostrip%20logos/Logo-Henkel-1023.svg"
                      alt="Henkel Logo"
                      height="106"
                      width="179"
                      loading="lazy"
                    />
                    <img
                      src="https://squirro.com/hubfs/WEBSITE/Global%20assets/Logostrip%20logos/Logo-Syntheticus-1123.svg"
                      alt="Syntheticus Logo"
                      height="106"
                      width="179"
                      loading="lazy"
                    />
                    <img
                      src="https://squirro.com/hubfs/WEBSITE/Global%20assets/Logostrip%20logos/Logo-ING-123.svg"
                      alt="ING Logo"
                      height="106"
                      width="179"
                      loading="lazy"
                    />
                    <img
                      src="https://squirro.com/hubfs/WEBSITE/Global%20assets/Logostrip%20logos/Logo-Helvetia-1023.svg"
                      alt="Helvetia Logo"
                      height="106"
                      width="179"
                      loading="lazy"
                    />
                    <img
                      src="https://squirro.com/hubfs/WEBSITE/Global%20assets/Logostrip%20logos/Logo-ocbc-bank-1123.svg"
                      alt="OCBC Bank Logo"
                      height="106"
                      width="179"
                      loading="lazy"
                    />
                    <img
                      src="https://squirro.com/hubfs/WEBSITE/Global%20assets/Logostrip%20logos/Logo-mubadala-1123.svg"
                      alt="Mubadala Logo"
                      height="106"
                      width="179"
                      loading="lazy"
                    />
                    <img
                      src="https://squirro.com/hubfs/WEBSITE/Global%20assets/Logostrip%20logos/Logo-indicia-1123.svg"
                      alt="Indicia Worldwide Logo"
                      height="106"
                      width="179"
                      loading="lazy"
                    />
                    <img
                      src="https://squirro.com/hubfs/WEBSITE/Global%20assets/Logostrip%20logos/Logo-HMRC-1123.svg"
                      alt="HMRC Logo"
                      height="106"
                      width="179"
                      loading="lazy"
                    />
                    <img
                      src="https://squirro.com/hubfs/WEBSITE/Global%20assets/Logostrip%20logos/Logo-candriam-1123.svg"
                      alt="Candriam Logo"
                      height="106"
                      width="179"
                      loading="lazy"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="relative rounded-lg text-cta-content flex justify-around items-center  flex-col sm:flex-row mt-[10rem] mb-[55px] text-white p-4">
          <img
            className="icon-wrapper"
            src="https://www.gartner.com/pi/vendorimages/squirro_1589195979665.png"
            alt="Squirro logo"
          />
          <div className="z-10">
            <h1 className="bg-clip-text text-transparent bg-gradient-to-r from-orange-500 to-orange-300 text-left text-[4rem] sm:text-[5rem] leading-[1.1] font-bold">
              Meet SquirroGPT
            </h1>
          </div>
          <div className="sm:max-w-[400px] sm:px-4 sm:py-8">
            <p className="text-sm">
              The first enterprise-ready Retrieval Augmented Generation (RAG)
              stack and Large Language Model (LLM) offering. SquirroGPT enables
              enterprises to benefit from safe and versatile Generative AI usage
              and is LLM agnostic.
            </p>
            <div className="cta-group flex-col sm:flex-row flex mt-8 ">
              <div className="btn-wrapper py-6 mr-4 btn-primary-wrapper btn-wrapper-md">
                <a
                  className="cta-button"
                  href="https://squirro.com/book-a-demo"
                >
                  Book a Demo
                </a>
              </div>
              <div className="btn-wrapper py-6 btn-outline-white-wrapper btn-wrapper-md">
                <a
                  className="cta-button"
                  href="https://squirro.com/why-you-need-retrieval-augmented-generation-in-2024"
                  target="_blank"
                  rel="noopener"
                >
                  Learn More
                </a>
              </div>
            </div>
          </div>
        </div>
        <div className="relative rounded-lg  mt-40 mb-14">
          <div className="flex flex-wrap justify-between">
            <div className="w-full max-w-[545px]">
              <ul className="flex flex-col p-0">
                <div className="tabs-container">
                  <div
                    className="tab-background rounded-lg"
                    style={backgroundStyle}
                    ref={backgroundRef}
                  ></div>
                  {tabData.map((tab, index) => (
                    <button
                      className={`relative flex flex-col text-start p-6 text-center rounded-lg items-start tab-button ${
                        activeTab === tab.id ? "active" : ""
                      }`}
                      onClick={() => setActiveTab(tab.id)}
                      ref={(el) => (tabsRef.current[index] = el)}
                    >
                      <div className="flex items-center">
                        {React.createElement(iconMapping[tab.icon], {
                          strokeWidth: 1,
                          className: "mr-4",
                          size: 28,
                          color: "#d14a20",
                        })}
                        <h3 className="mt-2 ml-0 text-2xl font-semibold text-[#d14a20] m-2 mt-2">
                          {tab.title}
                        </h3>
                      </div>
                      <p
                        className={`mb-4 ml-10 description-transition max-w-[400px] ${
                          activeTab === tab.id ? "description-visible" : ""
                        }`}
                      >
                        {tab.description}
                      </p>
                      {tab.listItems && activeTab === tab.id && (
                        <ul className="list-disc ml-10 list-inside">
                          {tab.listItems.map((item, index) => (
                            <li key={index}>{item}</li>
                          ))}
                        </ul>
                      )}
                    </button>
                  ))}
                </div>
              </ul>
            </div>
            <div className="w-full md:w-2/3 xl:max-w-[600px] max-w-[400px] h-auto rounded-lg">
              {tabData.map((tab) => (
                <div
                  key={tab.id}
                  className={`rounded-lg  ${
                    activeTab === tab.id ? "block" : "hidden"
                  }`}
                  role="tabpanel"
                >
                  <img
                    src={tab.imgUrl}
                    alt={tab.imgAlt}
                    className="max-w-full h-auto rounded-lg shadow"
                  />
                </div>
              ))}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
